name: "ddclient dynamic dns updater"
description: "ddclient extension for home assistant"
version: "1.0.0"
url: "https://github.com/alfonsocatanzaro/hass_ddclient"
slug: "hass_ddclient"
map:
  - config
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  file: ddclient.conf
schema:
  file: str