name: "Home assistant ddclient"
description: "Home assistant ddclient extension allows to use ddclient to perform automatic update of a various dynamic dns"
version: "1.0.1"
url: "https://github.com/alfonsocatanzaro/hass_ddclient"
slug: "ddclient"
map:
  - config
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  DDCLIENT_CONF: "ddclient.conf"
schema:
  DDCLIENT_CONF: "str"